baseURL = "https://kevindurb.github.io/blog/"
languageCode = "en-us"
title = "My Project Addiction"
theme = "github.com/theNewDynamic/gohugo-theme-ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "A log of various random projects"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  background_color_class = "bg-dark-blue"
  featured_image = "/main_splash.jpg"
  recent_posts_number = 10
