baseURL: "https://kevindurb.github.io/blog/"
languageCode: "en-us"
title: "My Project Addiction"
theme: "github.com/adityatelange/hugo-PaperMod"

DefaultContentLanguage: "en"
SectionPagesMenu: "main"
googleAnalytics: ""
enableRobotsTXT: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

params:
  comments: true
  showShareButtons: true
  showReadingTime: true
  homeInfoParams:
    Title: My Project Addiction
    Content: My writing place for random projects spanning a wide variety of subjects
  socialIcons:
    - name: github
      url: "https://github.com/kevindurb"
